
<table align="center" width=100%>
    <tr>
        <td width="20%">
            <img src="homework.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Take-Home <br>(Random Forest)
                    </b>
                </font>
            </div>
        </td>
        <td width="25%">
            <img src="GL-2.png">
        </td>
    </tr>
</table>

#### Import the required libraries

In [1]:
# type your code here
# type your code here
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import scipy 
import sklearn
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import confusion_matrix, accuracy_score,precision_score, classification_report,log_loss,roc_curve, roc_auc_score,cohen_kappa_score, f1_score,recall_score
from sklearn.model_selection import train_test_split, GridSearchCV
import statsmodels.api as sm 
from sklearn.datasets import make_classification
from collections import Counter
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve


#### Read the data

Load the csv file and print the first five observations.

In [2]:
# type your code here

In [3]:
df = pd.read_csv('seeds_dataset.csv')
df.head()

Area  Perimeter  Kernel_len  Kernel_width  Kernelgroove_len  Type
0  12.76      13.38       5.073         3.155             4.830     0
1  12.13      13.73       5.394         3.745             5.220     0
2  14.86      14.67       5.678         3.258             5.351     0
3  15.69      14.75       5.527         3.514             5.046     0
4  19.94      16.92       6.675         3.763             6.550     1

In [4]:
df.shape

(199, 6)

In [5]:
df.isnull().sum()

Area                0
Perimeter           0
Kernel_len          0
Kernel_width        0
Kernelgroove_len    0
Type                0
dtype: int64

**The data definition is as follows:** <br>

**Area**: Area of the wheat kernel 

**Perimeter**: Perimeter of the wheat kernel

**Kernel_len**: Length of the wheat kernel

**Kernel_width**: Width of the wheat kernel

**Kernelgroove_len**: Length of the wheat kernel groove

**Type**: Type of the wheat seed (0 = Kama Wheat, 1 = Rosa Wheat) (target/dependent variable)

Our objective is to predict whether the wheat seed is of Kama or Rosa type.

### Let's begin with some hands-on practice exercises

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Build a Random Forest model using the gini criterion. And obtain the number of correctly predicted wheat seeds in the test set</b>
                </font>
            </div>
        </td>
    </tr>
</table>

#### Consider the train-test split in the ratio 70:30 with random state = 1.

#### Split the data in train and test set.

#### Split the dependent and independent variables.

In [6]:
# Type your code

In [7]:
X = df.drop('Type', axis = 1)
y = df['Type']

xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=0.3, random_state=1)

#### Build a Random Forest tree model on the train set using 'gini' criterion.

In [8]:
rf = RandomForestClassifier(random_state=1, criterion='gini')

In [9]:
rf.fit(xtrain,ytrain)

ypred = rf.predict(xtest)

print(accuracy_score(ypred,ytest))

0.95


#### Let us plot the confusion matrix. The sum of the diagonal elements in the matrix corresponds to the total correct predictions.

In [10]:
confusion_matrix(ytest, ypred)

array([[36,  3],
       [ 0, 21]], dtype=int64)

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Select the optimal number for decision trees from the given list of values to build a random forest using entropy criterion
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the given list:**

no_of_trees = [6, 8, 10, 12, 14, 16]

In [11]:
# Type your code

In [26]:

# Define the range of candidate values for the number of trees (n_estimators)
param_grid = {'n_estimators': [6, 8, 10, 12, 14, 16]}

# Create a Random Forest Classifier with entropy criterion
rf_classifier = RandomForestClassifier(criterion='entropy', random_state=42)

# Create a grid search with cross-validation
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')

# Fit the grid search to your data
grid_search.fit(X, y)  # Replace X and y with your dataset and labels

# Get the best number of trees from the grid search
best_n_estimators = grid_search.best_params_['n_estimators']

print(f"The optimal number of decision trees is: {best_n_estimators}")


The optimal number of decision trees is: 16


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Identify the most important variable in the random forest build with the optimal number of trees obtained in Q3
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

Consider the train and test set in Q1.

First build the random forest with the `entropy` criterion and optimal number of trees (i.e. 8)

In [27]:
# Type your code

In [28]:
rf_classifier.fit(X,y)

RandomForestClassifier(criterion='entropy', random_state=42)

In [29]:
index_of_imp  = rf_classifier.feature_importances_.argmax()

In [30]:
X.columns[index_of_imp]

'Kernelgroove_len'

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Build a random forest containing ten trees and compute the precision and sensitivity of the model from the confusion matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

Consider the train and test set in Q1.

In [31]:
# Type your code

In [32]:
rf_classifier = RandomForestClassifier(criterion='entropy', random_state=42,n_estimators=10)

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [35]:
y_pred = rf_classifier.predict(X_test)

In [36]:
cm = confusion_matrix(y_test, y_pred)

In [37]:
cm

array([[24,  1],
       [ 1, 14]], dtype=int64)

In [38]:
sensitivity = cm[1][1]/(cm[1][1]+cm[1][0])
sensitivity

0.9333333333333333

In [39]:
specificity= cm[0][0]/(cm[0][0] + cm[0][1])
specificity

0.96

In [40]:
from sklearn.metrics import classification_report

In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        25
           1       0.93      0.93      0.93        15

    accuracy                           0.95        40
   macro avg       0.95      0.95      0.95        40
weighted avg       0.95      0.95      0.95        40



<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Build a random forest with entropy criterion such that each leaf node will contain at least three samples. Also calculate the f-1 score and accuracy of the model
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [38]:
# Type your code

In [39]:
rf_classifier = RandomForestClassifier(criterion='entropy', random_state=42,n_estimators=10,min_samples_leaf=3)
rf_classifier.fit(X_train, y_train)
y_pred = rf_classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)

In [40]:
cm

array([[24,  1],
       [ 1, 14]], dtype=int64)

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        25
           1       0.93      0.93      0.93        15

    accuracy                           0.95        40
   macro avg       0.95      0.95      0.95        40
weighted avg       0.95      0.95      0.95        40

